### ISSUE TITLE
I got error when kill MythicMobs

### ISSUE THREAD

**Issue by InnocentOongZ** [BerndiVader/MythicMobsQuestsModule#10]
[18:36:27] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Quests v2.8.6-b132
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:391) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityLiving.die(EntityLiving.java:986) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityLiving.damageEntity(EntityLiving.java:903) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityHuman.attack(EntityHuman.java:1002) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityPlayer.attack(EntityPlayer.java:1134) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1576) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(SourceFile:68) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(SourceFile:12) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.gmail.berndivader.questsMythicMobsKillObjective.QuestMMKillObjective.onMythicMobDeathEvent(QuestMMKillObjective.java:109) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	... 20 more

**Comment by InnocentOongZ** [comment]
Spigot 1.9.4-R0.1
Quest 2.8.6
MM 4.1.0

**Comment by BerndiVader** [comment]
Hello! Can you please test if the latest build fixed it for you?

**Comment by TOMCO984** [comment]
Hi,
I had the same error: Same versions of Spigot Quest and MM as @InnocentOongZ have. I have resolved the problem with the latest build of Quests (Build #157 Quests 2.9.6 : http://ci.ac3-servers.eu/job/Quests/157/) and with the latest version of MMQuest module. And Now it work perfectly.

**Comment by BerndiVader** [comment]
Thank you for reporting back.
