### ISSUE TITLE
MMQM requires updating for MM 4.4

### ISSUE THREAD

**Issue by SXRWahrheit** [BerndiVader/MythicMobsQuestsModule#18]
```
[21:27:42] [Server thread/INFO]: Wahrheit issued server command: /questadmin finish Wahrheit EliteMelee
[21:27:42] [Server thread/INFO]: [PLAYERCOMMAND} Wahrheit: [2405 76 2834] => "/questadmin finish Wahrheit EliteMelee"
[21:27:42] [Server thread/WARN]: java.lang.NullPointerException
[21:27:42] [Server thread/WARN]: 	at com.gmail.berndivader.mythicmobsquests.MythicMobsItemReward.giveReward(MythicMobsItemReward.java:35)
[21:27:42] [Server thread/WARN]: 	at me.blackvein.quests.Quest.completeQuest(Quest.java:498)
[21:27:42] [Server thread/WARN]: 	at me.blackvein.quests.Quests.adminFinish(Quests.java:1055)
[21:27:42] [Server thread/WARN]: 	at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:714)
[21:27:42] [Server thread/WARN]: 	at me.blackvein.quests.Quests.onCommand(Quests.java:689)
[21:27:42] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:27:42] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:27:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[21:27:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[21:27:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[21:27:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:27:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:27:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:27:42] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:27:42] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:27:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[21:27:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[21:27:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[21:27:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[21:27:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[21:27:42] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by BerndiVader** [comment]
dev branch supports mythicmobs 4.4

https://github.com/BerndiVader/MythicMobsQuestsModule/tree/dev
