### ISSUE TITLE
NPE on mob kill

### ISSUE THREAD

**Issue by SXRWahrheit** [BerndiVader/MythicMobsQuestsModule#2]
```
[00:54:31] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Quests v2.7.6-b120
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:394) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1079) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntitySkeletonAbstract.die(EntitySkeletonAbstract.java:120) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntitySkeletonWither.die(EntitySkeletonWither.java:48) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:933) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityMonster.damageEntity(EntityMonster.java:44) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:1023) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1158) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1578) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at com.gmail.berndivader.questsMythicMobsKillObjective.QuestMMKillObjective.onMythicMobDeathEvent(QuestMMKillObjective.java:73) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-3fb9445-6e3cec8]
	... 23 more

```

Quest YAML:

```
  custom1:
    name: Hunt the Skeletal Dark Knight
    ask-message: Will you help us kill a Skeletal Dark Knight?
    finish-message: Thank you for your help!
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs
              count: 1
              data:
                Killable Types: SkeletalDarkKnight
                Objective Name: Kill a Skeletal Dark Knight
    rewards:
      items:
      - name-DIAMOND:amount-3
      money: 50
```

**Comment by SXRWahrheit** [comment]
Just tried b121 of Quests, same issue. Using the version of Quests on GitHub results in the objective not even being listed.

**Comment by BerndiVader** [comment]
Hello @SXRWahrheit ! The quest yaml you posted, have nothing to do with this addon. use the ingame editor or if you prefer to edit the yaml use this template:

https://pastebin.com/gGw4gDyL

For mob level you can use ranged values like: 1-10 or just a single value.

I did a test with Quests 2.7.3 and 2.7.6 both working.

**Comment by SXRWahrheit** [comment]
That was the yaml generated by the in-game editor when I used it to make a quest. Could you post the yaml from one you successfully create?

Edit: Your pastebin link originally got hidden by an extension. I'll try that and report back. :)

**Comment by SXRWahrheit** [comment]
Still nothing (also tried with mob level 0 as in example):

```
  custom1:
    name: Hunt the Skeletal Dark Knight
    ask-message: Will you help us kill a Skeletal Dark Knight?
    finish-message: Thank you for your help!
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 1
              data:
                Objective Name: Kill a Skeletal Dark Knight
                Internal Mobnames: SkeletalDarkKnight
```
```
[16:17:38] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Quests v2.7.6-b121
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:394) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1079) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntitySkeletonAbstract.die(EntitySkeletonAbstract.java:120) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntitySkeletonWither.die(EntitySkeletonWither.java:48) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:933) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityMonster.damageEntity(EntityMonster.java:44) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:1023) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1158) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1578) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at com.gmail.berndivader.questsMythicMobsKillObjective.QuestMMKillObjective.onMythicMobDeathEvent(QuestMMKillObjective.java:73) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor356.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-3fb9445-6e3cec8]
	... 23 more
```

**Comment by BerndiVader** [comment]
Hello @SXRWahrheit ! Please note that there are 3 required values. Mob Level (set it to 0 to ignore), the internal mythicmobs mob names, and the amount. In your config is the mob level missing. Here is an example of a valid yaml configuration:

          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 5
              data:
                Mob Level: '0'
                Objective Name: Kill Some Mobs
                Internal Mobnames: MythicMonkey

About the issue you postet, that the module is not loading for the latest dev build of quests, i will look into it and update it for the quests devbuild.

**Comment by SXRWahrheit** [comment]
I just tried using this yaml and the Quests build you have on GitHub:

```
  custom1:
    name: Hunt the Skeletal Dark Knight
    ask-message: Will you help us kill a Skeletal Dark Knight?
    finish-message: Thank you for your help!
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 1
              data:
                Objective Name: Kill a Skeletal Dark Knight
                Internal Mobnames: SkeletalDarkKnight
                Mob Level: 0-10
    rewards:
      items:
      - name-DIAMOND:amount-3
      money: 50
```

I also tried this:

```
  custom1:
    name: Hunt the Skeletal Dark Knight
    ask-message: Will you help us kill a Skeletal Dark Knight?
    finish-message: Thank you for your help!
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 1
              data:
                Mob Level: '0'
                Objective Name: Kill a Skeletal Dark Knight
                Internal Mobnames: SkeletalDarkKnight
    rewards:
      items:
      - name-DIAMOND:amount-3
      money: 50
```

There was no error in the console this time, but the quest still does not complete.

**Comment by BerndiVader** [comment]
Hello @SXRWahrheit ! I did an intense testing now. Using Spigot 1.8.8-1.11.2 mythicmobs 2.5.1 - 4.1.0 and quests 2.7.3 official 2.7.6 inkl. 2.7.6 jenkins b121. Everything was good, no errors and the objective always finished.

My mob:

```
SkeletalDarkKnight:
  Type: zombie
  Display: "a Skeletal Dark Knight"
  AIGoalSelectors:
  - 0 clear
```

My quests yaml:

```
  custom2:
    name: mmtest
    ask-message: kill me some mythicmobs
    finish-message: welldone!
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 1
              data:
                Mob Level: '0'
                Objective Name: Kill a Skeletal Dark Knight
                Internal Mobnames: SkeletalDarkKnight
```

**Comment by SXRWahrheit** [comment]
Odd - will test and get back to you.

**Comment by SXRWahrheit** [comment]
It looks like it may have been a Spigot version issue - working now. Thanks! I also didn't previously have the mob level indicated. It might be worth adding all this to the readme. I could do a pull request if you want.

**Comment by BerndiVader** [comment]
That would be very nice from you. I build in some better npe handling. Also the ability to use ANY for all mythicmobs mobs.
