### ISSUE TITLE
Some Errors.

### ISSUE THREAD

**Issue by kleinesgumi** [BerndiVader/MythicMobsQuestsModule#24]
Server version: 1.8.8
Quests version: 3.5.9-b586
Citizens version: 2.0.24-SNAPSHOT (build 1605)
Addon version: 4.1.1

on mythicmobs mob kill:
`
[17:07:41 ERROR]: Could not pass event EntityDeathEvent to Quests v3.5.9-b586
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:378) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:874) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityZombie.die(EntityZombie.java:561) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:812) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityZombie.damageEntity(EntityZombie.java:167) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: me.blackvein.quests.Quester.getCurrentQuests()Ljava/util/concurrent/ConcurrentHashMap;
        at com.gmail.berndivader.mythicmobsquests.MythicMobsKillObjective.onMythicMobDeathEvent(MythicMobsKillObjective.java:73) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]
        ... 23 more
`

on NPC rightclick:
`
[18:00:10 ERROR]: Could not pass event NPCRightClickEvent to Quests v3.5.9-b586
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:431) [Citizens.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1315) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: me.blackvein.quests.Quester.getCurrentQuests()Ljava/util/concurrent/ConcurrentHashMap;
        at com.gmail.berndivader.mythicmobsquests.MythicItemDeliverObjective.onNPCInteract(MythicItemDeliverObjective.java:60) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]
        ... 24 more
`

**Comment by BerndiVader** [comment]
Thanks for report. Update Quests to 3.6.x should fix the issue.

**Comment by kleinesgumi** [comment]
@BerndiVader on the latest jenkis build: 
```
[01:15:00 ERROR]: [Quests] Unable to load module from file: MythicMobsQuests.jar
[01:15:00 WARN]: java.lang.reflect.InvocationTargetException
[01:15:00 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[01:15:00 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[01:15:00 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:15:00 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[01:15:00 WARN]:        at me.blackvein.quests.Quests.loadModule(Quests.java:538)
[01:15:00 WARN]:        at me.blackvein.quests.Quests.loadModules(Quests.java:466)
[01:15:00 WARN]:        at me.blackvein.quests.Quests$1.run(Quests.java:439)
[01:15:00 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[01:15:00 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[01:15:00 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[01:15:00 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[01:15:00 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[01:15:00 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[01:15:00 WARN]:        at java.lang.Thread.run(Thread.java:748)
[01:15:00 WARN]: Caused by: java.lang.NoSuchFieldError: datamap
[01:15:00 WARN]:        at com.gmail.berndivader.mythicmobsquests.MythicMobsItemReward.addDataAndDefault(MythicMobsItemReward.java:55)
[01:15:00 WARN]:        at com.gmail.berndivader.mythicmobsquests.MythicMobsItemReward.<init>(MythicMobsItemReward.java:22)
[01:15:00 WARN]:        ... 14 more

```

**Comment by kleinesgumi** [comment]
@BerndiVader you Questmodule supports the 4.5.1 mythicmobs version? the release dates from addon and Mythicmobs are different.

**Comment by BerndiVader** [comment]
Hi! Everything should be solved with the latest build.

**Comment by kleinesgumi** [comment]
now if set any mythicmobs monster as objective its not counting an this error comes up:

> [07:50:00 ERROR]: Could not pass event EntityDeathEvent to Quests v3.6.0-b631
> org.bukkit.event.EventException
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
>         at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:378) [server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:874) [server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.EntityZombie.die(EntityZombie.java:561) [server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:812) [server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.EntityZombie.damageEntity(EntityZombie.java:167) [server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
>         at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
> Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
>         at com.gmail.berndivader.mythicmobsquests.MythicMobsKillObjective.onMythicMobDeathEvent(MythicMobsKillObjective.java:70) ~[?:?]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]
>         ... 23 more
