### ISSUE TITLE
Errors 1.13.2

### ISSUE THREAD

**Issue by Mrkhris** [BerndiVader/MythicMobsQuestsModule#25]
Server version: 1.13.2
Quests version: 3.5.9-b586
Citizens version: 2.0.24-SNAPSHOT (build 1604)
Addon version: Last updated 10 days ago on GitHub

When I try to click right click on the quest, where the job is to murder the mobs from MM, I get this error message

[23:54:41] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to Quests v3.5.9-b586
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:431) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1830) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: me.blackvein.quests.Quester.getCurrentQuests()Ljava/util/concurrent/ConcurrentHashMap;
	at com.gmail.berndivader.mythicmobsquests.MythicItemDeliverObjective.onNPCInteract(MythicItemDeliverObjective.java:60) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	... 24 more

I want to say that I appreciate your work and your work! This is really something cool, keep up the good work and thanks for such a great module for Quests

**Comment by Mrkhris** [comment]
The error is solved by updating the Quests to 3.6.0, you can download it here - http://ci.ac3-servers.eu/job/Quests/
