### ISSUE TITLE
Notifier msg no work

### ISSUE THREAD

**Issue by Mrkhris** [BerndiVader/MythicMobsQuestsModule#26]
Server version: 1.13.2
Quests version: 3.6.0 #609
Citizens version: 2.0.24-SNAPSHOT (build 1604)
Addon version: Last updated 10 days ago on GitHub

There is no error in the console, but it just doesn't work for me. In the chat only writes the name of the mob

My quests
  custom1:
    name: Zombie
    npc-giver-id: 60
    ask-message: zombie
    finish-message: zombie
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 1
              data:
                Mob Level: '0'
                Internal Mobnames: mob1
                Notifier enabled: 'true'
                Notifier msg: Killed %c% out of %s%
                Objective Name: Zombie

**Comment by Mrkhris** [comment]
![1bjmz8f8k_8](https://user-images.githubusercontent.com/46727551/51211936-008ae680-1928-11e9-9d03-d09b16922e8b.jpg)

**Comment by Mrkhris** [comment]
By the way, when I create a stage of "Murder mob MM" through the game, I get this error. The error ceases to appear when you re-after the 1st time trying to specify the target " Murder MM"

[Quests] Plugin Quests v3.6.0-b609 generated an exception whilst handling conversation input
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at me.blackvein.quests.prompts.CreateStagePrompt$ObjectiveCustomDataListPrompt.getPromptText(CreateStagePrompt.java:3985) ~[?:?]
	at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:284) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at org.bukkit.craftbukkit.v1_13_R2.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:60) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1203) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.PlayerConnection$2.evaluate(PlayerConnection.java:1497) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at org.bukkit.craftbukkit.v1_13_R2.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:913) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**Comment by Mrkhris** [comment]
![51211936-008ae680-1928-11e9-9d03-d09b16922e8b](https://user-images.githubusercontent.com/46727551/51212851-9293ee80-192a-11e9-820d-95fc1223abe8.jpg)
![51211936-008ae680-1928-11e9-9d03-d09b16922e8b](https://user-images.githubusercontent.com/46727551/51212977-eacaf080-192a-11e9-8f55-392eab6f4722.jpg)

I completely reset the plugin and its folder - the problem remained

  custom1:
    name: dsfds
    npc-giver-id: 60
    ask-message: gsdf
    finish-message: sdfdsf
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 1
              data:
                Mob Level: '0'
                Objective Name: 'lox'
                Internal Mobnames: mob1
                Notifier enabled: 'true'
                Notifier msg: Ti krutou

**Comment by Mrkhris** [comment]
I even reinstalled all the files again and inserted your original quest, which is on GitHub
![googlelogo_color_272x92dp](https://user-images.githubusercontent.com/46727551/51263850-24046e80-19c6-11e9-9168-9bc35735ae4d.png)
But Notifier msg don't works(
Mythismobs - MythicMobs-4.5.1
Quests - 3.6.0-b610
Citizens - 2.0.24-SNAPSHOT (build 1605)
Vault - 1.7.1-b91
Spigot 1.12.1 and 1.13.2
