### ISSUE TITLE
Kill event not passing

### ISSUE THREAD

**Issue by SXRWahrheit** [BerndiVader/MythicMobsQuestsModule#46]
```
[09:26:49] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Quests v3.9.5-b130
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
	at com.gmail.berndivader.mythicmobsquests.NMSUtils.getActiveMobLevel(NMSUtils.java:122) ~[?:?]
	at com.gmail.berndivader.mythicmobsquests.MythicMobsKillObjective.onMythicMobDeathEvent(MythicMobsKillObjective.java:60) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor932.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-116]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-116]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-116]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-116]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:794) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.EntityLiving.d(EntityLiving.java:1489) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.EntityLiving.die(EntityLiving.java:1417) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1261) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.EntityEnderman.damageEntity(EntityEnderman.java:336) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.EntityHuman.attack(EntityHuman.java:1092) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.EntityPlayer.attack(EntityPlayer.java:1861) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2139) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-116]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-116]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

[Sun, 9. Aug 2020 09:52:23 CDT INFO] Quests version 3.9.5-b130
[Sun, 9. Aug 2020 09:52:38 CDT INFO] MythicMobs version 4.10.0-SNAPSHOT-3347
MMQM build 391
Paper 1.16.1-116

**Comment by BerndiVader** [comment]
Sounds like #42. Do you use latest build?

**Comment by SXRWahrheit** [comment]
Of MMQM? Yes.

**Comment by SXRWahrheit** [comment]
Issue resolved by re-downloading the module - something got lost in the tubes!
