### ISSUE TITLE
Error zNPCs interact? 

### ISSUE THREAD

**Issue by wryel2000** [BerndiVader/MythicMobsQuestsModule#54]
I dont have any question using (delivery or Interact witha a npc)
but i have spam this error in console.

[19:43:41 ERROR]: Could not pass event NPCInteractEvent to Quests v5.0.2-b469
java.lang.NoClassDefFoundError: io/github/znetworkw/znpcservers/npc/interaction/NPCInteractEvent
        at org.browsit.mythicmobsquests.events.MythicMobsZNPCsPlusEvents_v1.onNPCInteract(MythicMobsZNPCsPlusEvents_v1.java:15) ~[?:?]
        at org.browsit.mythicmobsquests.MythicMobsItemDeliverObjective.handleEvents(MythicMobsItemDeliverObjective.java:88) ~[?:?]
        at org.browsit.mythicmobsquests.MythicMobsItemDeliverObjective.lambda$new$0(MythicMobsItemDeliverObjective.java:45) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.github.gonalez.znpcs.user.ZUser$ZNPCSocketDecoder.lambda$decode$1(ZUser.java:123) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by wryel2000** [comment]
UP? Anyone?
