### ISSUE TITLE
(Noob) Having an issue Loading Provided Jar File

### ISSUE THREAD

**Issue by Dominizo** [BerndiVader/MythicMobsQuestsModule#7]
[03:29:37] [Server thread/ERROR]: Could not load 'plugins/QuestMMKillObjective (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more

**Comment by BerndiVader** [comment]
Hello! Delete all QuestMMKIllObjective jars in your plugins folder and download it again, but this time copy it into `plugins\Quests\modules`

**Comment by Dominizo** [comment]
THANK YOU SO MUCH! IT WORKED! Has anyone made a video explaining how to set up Mythical Mobs to spawn in a certain area or is that done through Quests?
